# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 14:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CodechefRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('long_global', models.IntegerField(null=True)),
                ('long_local', models.IntegerField(null=True)),
                ('long_rating', models.FloatField(null=True)),
                ('short_rating', models.FloatField(null=True)),
                ('short_global', models.IntegerField(null=True)),
                ('short_local', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeforcesRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('position', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HackerrankRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('codechef_handle', models.CharField(blank=True, max_length=100)),
                ('codeforces_handle', models.CharField(blank=True, max_length=100)),
                ('hackerrank_handle', models.CharField(blank=True, max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('dp', models.ImageField(upload_to=b'dp')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.Branch')),
                ('codechef_rank', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.CodechefRank')),
                ('codeforces_rank', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.CodeforcesRank')),
                ('hackerrank_rank', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.HackerrankRank')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.Institute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
