# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='codechef_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.CodechefRank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='codeforces_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.CodeforcesRank'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hackerrank_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.HackerrankRank'),
        ),
    ]
