# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160618_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codechefrank',
            name='handle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='codeforcesrank',
            name='handle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='hackerrankrank',
            name='handle',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
